import { StyleSheet } from "react-native";
const PointDetailComponentStyles = StyleSheet.create({
  scrollContainer: {
    backgroundColor: "#2B2B2B",
  },

  CardContainer: {
    marginTop: 90,
    width: "90%",
    alignSelf: "center",
  },
  pointDetailCard: {
    backgroundColor: "rgba(251, 243, 228, 0.85)",
    marginBottom: 20,
  },

  title: {
    marginRight: "auto",
    marginLeft: "auto",
    fontSize: 30,
    fontWeight: "bold",
    marginTop: 15,
    marginBottom: 15,
  },
  subtitle: {
    color: "rgb(16, 86, 82)",
    fontWeight: "bold",
    marginLeft: 20,
    marginTop: 10,
    marginBottom: 10,
  },
  textDate: {
    color: "black",
    fontWeight: "bold",
    marginLeft: 40,
    marginTop: 10,
    marginBottom: 10,
  },
  textPoint: {
    color: "rgb(16, 86, 82)",
    fontWeight: "bold",
    marginLeft: "auto",
    marginRight: 40,
    marginTop: 10,
    marginBottom: 10,
    textAlign: "right",
  },
  currentPoint: {
    marginLeft: "auto",
    marginRight: 40,
    marginBottom: 20,
    marginTop: 20,
    fontSize: 33,
    color: "white",
    fontWeight: "bold",
  },
  currentPointText: {
    color: "black",
    fontWeight: "bold",
    marginLeft: 40,
    marginTop: 10,
    marginBottom: 10,
  },
  point: {
    marginLeft: "auto",
    marginRight: 20,
    marginBottom: 20,
    marginTop: 20,
    fontSize: 33,
    color: "white",
    fontWeight: "bold",
  },
  pointDetail: {
    color: "rgb(16, 86, 82)",
    marginLeft: 20,
    marginTop: 10,
    marginBottom: 10,
    fontSize: 13,
  },
  text: {
    color: "black",
    marginLeft: "auto",
    marginRight: 20,
    marginTop: 10,
    marginBottom: 10,
  },
  tabContainer: {
    width: "100%",
    height: 70,
    backgroundColor: "rgba(234, 234, 234,0.8)",
    padding: 10,
    flexDirection: "row",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  tabButton: {
    height: 55,
    justifyContent: "center",
    alignItems: "center",
    width: "22%",
    padding: 5,
    margin: 5,
    textAlign: "center",
    borderRadius: 20,
    borderColor: "rgba(234, 234, 234,0.7)",
    borderWidth: 2,
  },
  tabSelectedButton: {
    height: 55,
    justifyContent: "center",
    alignItems: "center",
    width: "22%",
    padding: 5,
    backgroundColor: "rgba(234, 234, 234,0.7)",
    margin: 5,
    textAlign: "center",
    borderRadius: 20,
    borderColor: "#8D2828",
    borderWidth: 2,
  },
  tabText: {
    textAlign: "center",
    fontSize: 14,
    color: "#8D2828",
    marginTop: 3,
    padding: 0,
    fontWeight: "bold",
  },
  tabIcon: {
    justifyContent: "center",
  },
});
export default PointDetailComponentStyles;
